### PR TITLE
Reintroduce FabricShieldEnchantment

### LINKED ISSUE #82: Shield enchant target is broken outside dev environment / Reflection Enchantment Broken
Shield enchantments cause crashes outside the development environment in 1.5.3-1.18. in 1.18.2
```
[12:24:41] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
java.lang.AbstractMethodError: Receiver class net.minecraft.enchantment.EnchantmentTarget$15 does not define or inherit an implementation of the resolved method 'abstract boolean isAcceptableItem(net.minecraft.item.Item)' of abstract class net.minecraft.enchantment.EnchantmentTarget.
	at net.minecraft.enchantment.Enchantment.isAcceptableItem(Enchantment.java:121) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.command.EnchantCommand.execute(EnchantCommand.java:48) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.command.EnchantCommand.method_13240(EnchantCommand.java:35) ~[minecraft-project-@-merged-named.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager.java:222) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler.java:1134) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler.java:1120) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onChatMessage(ServerPlayNetworkHandler.java:1106) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket.java:48) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket.java:31) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:26) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:22) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:150) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:29) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:787) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1751) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:126) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:772) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:768) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:134) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:751) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:687) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:293) ~[minecraft-project-@-merged-named.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### PR DESCRIPTION
**Pull request by LimonBlaze**
Managed to reintroduce enchantment support, fixes #82.
The original problem should be caused by unnecessarily adding the `EnchantmentTargetMixin` to `mixins.json`.

### CODE REVIEW

**Comment by CringeStar** [comment]
Thanks! I will merge after Github runs its tests. I'll also test the mod itself once I get home.

**Comment by LimonBlaze** [comment]
By the way, #99 seemed accidentally invalidated the whole `ShieldBlockCallback`.
I found the issue while testing the builtin enchantment.
Is that an intended temporary fix or a mistake?

**Comment by CringeStar** [comment]
Can you elabirate on invalidated? Does it not work now or is there a bug with it?

**Comment by LimonBlaze** [comment]
https://github.com/CrimsonDawn45/Fabric-Shield-Lib/blob/be2cd8ce91ae2c7ddc1d0cf273b6d163d0283680/src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityMixin.java#L33
The invocation is commented out, thus the event is not working at all.

**Comment by CringeStar** [comment]
Oh, must've forgotten to uncomment that, thanks for noticing!

**Pull request merged**
